# Generated by Django 5.1.7 on 2025-03-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('hotline', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Important', 'Important'), ('Fire Department', 'Fire Department'), ('Hospitals', 'Hospitals'), ('Shelters', 'Shelters')], max_length=50)),
            ],
        ),
    ]
